In [5]:
import pandas as pd

df = pd.read_csv('titanic_data_updated.csv')

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split


df = pd.read_csv('titanic_data_updated.csv')

# 2. Separate features (X) and target (y)
X = df.drop('Name', axis=1) # Replace with your actual target column
y = df['Name']

# 3. Create the train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.preprocessing import OrdinalEncoder
pclass_encoder=OrdinalEncoder(categories=[['third','second','first']])
pclass_encoder.fit(X_train[['Pclass']])
X_train['encoded_Pclass']=pclass_encoder.transform(X_train[['Pclass']]).ravel()
X_test['encoded_Pclass']=pclass_encoder.transform(X_test[['Pclass']]).ravel()

In [8]:
X_train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_Pclass
331,332,no,first,male,45.5,0,0,113043,28.5000,C124,S,2.0
733,734,no,second,male,23.0,0,0,28425,13.0000,NaN,S,1.0
382,383,no,third,male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S,0.0
704,705,no,third,male,26.0,1,0,350025,7.8542,NaN,S,0.0
813,814,no,third,female,6.0,4,2,347082,31.2750,NaN,S,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,third,female,21.0,0,0,343120,7.6500,NaN,S,0.0
270,271,no,first,male,NaN,0,0,113798,31.0000,NaN,S,2.0
860,861,no,third,male,41.0,2,0,350026,14.1083,NaN,S,0.0
435,436,yes,first,female,14.0,1,2,113760,120.0000,B96 B98,S,2.0
102,103,no,first,male,21.0,0,1,35281,77.2875,D26,S,2.0

In [9]:
X_test

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_Pclass
709,710,yes,third,male,NaN,1,1,2661,15.2458,NaN,C,0.0
439,440,no,second,male,31.0,0,0,C.A. 18723,10.5000,NaN,S,1.0
840,841,no,third,male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,0.0
720,721,yes,second,female,6.0,0,1,248727,33.0000,NaN,S,1.0
39,40,yes,third,female,14.0,1,0,2651,11.2417,NaN,C,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,no,third,male,17.0,0,0,STON/O 2. 3101274,7.1250,NaN,S,0.0
773,774,no,third,male,NaN,0,0,2674,7.2250,NaN,C,0.0
25,26,yes,third,female,38.0,1,5,347077,31.3875,NaN,S,0.0
84,85,yes,second,female,17.0,0,0,SO/C 14885,10.5000,NaN,S,1.0
10,11,yes,third,female,4.0,1,1,PP 9549,16.7000,G6,S,0.0

In [10]:
from sklearn.preprocessing import OneHotEncoder
sex_ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sex_ohe.fit(X_train[['Sex']])
encoded_df=sex_ohe.transform(X_train[['Sex']])
X_train=pd.concat([X_train,encoded_df],axis=1)
X_train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_Pclass,Sex_female,Sex_male
331,332,no,first,male,45.5,0,0,113043,28.5000,C124,S,2.0,0.0,1.0
733,734,no,second,male,23.0,0,0,28425,13.0000,NaN,S,1.0,0.0,1.0
382,383,no,third,male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S,0.0,0.0,1.0
704,705,no,third,male,26.0,1,0,350025,7.8542,NaN,S,0.0,0.0,1.0
813,814,no,third,female,6.0,4,2,347082,31.2750,NaN,S,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,third,female,21.0,0,0,343120,7.6500,NaN,S,0.0,1.0,0.0
270,271,no,first,male,NaN,0,0,113798,31.0000,NaN,S,2.0,0.0,1.0
860,861,no,third,male,41.0,2,0,350026,14.1083,NaN,S,0.0,0.0,1.0
435,436,yes,first,female,14.0,1,2,113760,120.0000,B96 B98,S,2.0,1.0,0.0
102,103,no,first,male,21.0,0,1,35281,77.2875,D26,S,2.0,0.0,1.0

In [11]:
from sklearn.preprocessing import OneHotEncoder
emberked_ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
emberked_ohe.fit(X_train[['Embarked']])
encoded_df=emberked_ohe.transform(X_train[['Embarked']])
X_train=pd.concat([X_train,encoded_df],axis=1)
X_train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
331,332,no,first,male,45.5,0,0,113043,28.5000,C124,S,2.0,0.0,1.0,0.0,0.0,1.0,0.0
733,734,no,second,male,23.0,0,0,28425,13.0000,NaN,S,1.0,0.0,1.0,0.0,0.0,1.0,0.0
382,383,no,third,male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
704,705,no,third,male,26.0,1,0,350025,7.8542,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
813,814,no,third,female,6.0,4,2,347082,31.2750,NaN,S,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,third,female,21.0,0,0,343120,7.6500,NaN,S,0.0,1.0,0.0,0.0,0.0,1.0,0.0
270,271,no,first,male,NaN,0,0,113798,31.0000,NaN,S,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,861,no,third,male,41.0,2,0,350026,14.1083,NaN,S,0.0,0.0,1.0,0.0,0.0,1.0,0.0
435,436,yes,first,female,14.0,1,2,113760,120.0000,B96 B98,S,2.0,1.0,0.0,0.0,0.0,1.0,0.0
102,103,no,first,male,21.0,0,1,35281,77.2875,D26,S,2.0,0.0,1.0,0.0,0.0,1.0,0.0

In [12]:
print(X_train.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'encoded_Pclass', 'Sex_female',
       'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S', 'Embarked_nan'],
      dtype='object')

In [13]:
X_train.drop(['Pclass', 'Sex', 'Embarked'], axis=1, inplace=True, errors='ignore')
X_train

,PassengerId,Survived,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan
331,332,no,45.5,0,0,113043,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,0.0
733,734,no,23.0,0,0,28425,13.0000,NaN,1.0,0.0,1.0,0.0,0.0,1.0,0.0
382,383,no,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
704,705,no,26.0,1,0,350025,7.8542,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
813,814,no,6.0,4,2,347082,31.2750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,21.0,0,0,343120,7.6500,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0
270,271,no,NaN,0,0,113798,31.0000,NaN,2.0,0.0,1.0,0.0,0.0,1.0,0.0
860,861,no,41.0,2,0,350026,14.1083,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
435,436,yes,14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,0.0
102,103,no,21.0,0,1,35281,77.2875,D26,2.0,0.0,1.0,0.0,0.0,1.0,0.0

In [14]:
X_train['Cabin'].value_counts()

Cabin
C23 C25 C27    4
C22 C26        3
F2             3
G6             3
B96 B98        3
              ..
A14            1
D49            1
C87            1
D56            1
C62 C64        1
Name: count, Length: 117, dtype: int64

In [15]:
X_train['Cabin'].value_counts()

Cabin
C23 C25 C27    4
C22 C26        3
F2             3
G6             3
B96 B98        3
              ..
A14            1
D49            1
C87            1
D56            1
C62 C64        1
Name: count, Length: 117, dtype: int64

In [16]:
X_train['Cabin_Deck']=X_train['Cabin'].astype(str).str[0]
X_train

,PassengerId,Survived,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_Pclass,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Embarked_nan,Cabin_Deck
331,332,no,45.5,0,0,113043,28.5000,C124,2.0,0.0,1.0,0.0,0.0,1.0,0.0,C
733,734,no,23.0,0,0,28425,13.0000,NaN,1.0,0.0,1.0,0.0,0.0,1.0,0.0,n
382,383,no,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,n
704,705,no,26.0,1,0,350025,7.8542,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,n
813,814,no,6.0,4,2,347082,31.2750,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,21.0,0,0,343120,7.6500,NaN,0.0,1.0,0.0,0.0,0.0,1.0,0.0,n
270,271,no,NaN,0,0,113798,31.0000,NaN,2.0,0.0,1.0,0.0,0.0,1.0,0.0,n
860,861,no,41.0,2,0,350026,14.1083,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,n
435,436,yes,14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,0.0,0.0,0.0,1.0,0.0,B
102,103,no,21.0,0,1,35281,77.2875,D26,2.0,0.0,1.0,0.0,0.0,1.0,0.0,D

In [17]:
X_train['Cabin_Deck'].value_counts()

Cabin_Deck
n    553
C     52
B     38
E     24
D     19
F     12
A     10
G      3
T      1
Name: count, dtype: int64

In [18]:
X_test['Cabin_Deck']=X_test['Cabin'].astype(str).str[0]
X_test

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_Pclass,Cabin_Deck
709,710,yes,third,male,NaN,1,1,2661,15.2458,NaN,C,0.0,n
439,440,no,second,male,31.0,0,0,C.A. 18723,10.5000,NaN,S,1.0,n
840,841,no,third,male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,0.0,n
720,721,yes,second,female,6.0,0,1,248727,33.0000,NaN,S,1.0,n
39,40,yes,third,female,14.0,1,0,2651,11.2417,NaN,C,0.0,n
...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,no,third,male,17.0,0,0,STON/O 2. 3101274,7.1250,NaN,S,0.0,n
773,774,no,third,male,NaN,0,0,2674,7.2250,NaN,C,0.0,n
25,26,yes,third,female,38.0,1,5,347077,31.3875,NaN,S,0.0,n
84,85,yes,second,female,17.0,0,0,SO/C 14885,10.5000,NaN,S,1.0,n
10,11,yes,third,female,4.0,1,1,PP 9549,16.7000,G6,S,0.0,G

In [19]:
from sklearn.preprocessing import OneHotEncoder

deck_ohe=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')

deck_ohe.fit(X_train[['Cabin_Deck']])
encoded_df=deck_ohe.transform(X_train[['Cabin_Deck']])
X_train=pd.concat([X_train,encoded_df],axis=1)
X_train

,PassengerId,Survived,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_Pclass,Sex_female,...,Embarked_nan,Cabin_Deck,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
331,332,no,45.5,0,0,113043,28.5000,C124,2.0,0.0,...,0.0,C,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,734,no,23.0,0,0,28425,13.0000,NaN,1.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
382,383,no,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
704,705,no,26.0,1,0,350025,7.8542,NaN,0.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
813,814,no,6.0,4,2,347082,31.2750,NaN,0.0,1.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,21.0,0,0,343120,7.6500,NaN,0.0,1.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
270,271,no,NaN,0,0,113798,31.0000,NaN,2.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
860,861,no,41.0,2,0,350026,14.1083,NaN,0.0,0.0,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
435,436,yes,14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,...,0.0,B,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,103,no,21.0,0,1,35281,77.2875,D26,2.0,0.0,...,0.0,D,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [20]:
encoded_df=deck_ohe.transform(X_test[['Cabin_Deck']])
X_test=pd.concat([X_test,encoded_df],axis=1)
X_test

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,...,encoded_Pclass,Cabin_Deck,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
709,710,yes,third,male,NaN,1,1,2661,15.2458,NaN,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
439,440,no,second,male,31.0,0,0,C.A. 18723,10.5000,NaN,...,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
840,841,no,third,male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
720,721,yes,second,female,6.0,0,1,248727,33.0000,NaN,...,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39,40,yes,third,female,14.0,1,0,2651,11.2417,NaN,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,no,third,male,17.0,0,0,STON/O 2. 3101274,7.1250,NaN,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
773,774,no,third,male,NaN,0,0,2674,7.2250,NaN,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
25,26,yes,third,female,38.0,1,5,347077,31.3875,NaN,...,0.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
84,85,yes,second,female,17.0,0,0,SO/C 14885,10.5000,NaN,...,1.0,n,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,11,yes,third,female,4.0,1,1,PP 9549,16.7000,G6,...,0.0,G,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [21]:
X_train.drop('Cabin_Deck',axis=1,inplace=True)
X_train

,PassengerId,Survived,Age,SibSp,Parch,Ticket,Fare,Cabin,encoded_Pclass,Sex_female,...,Embarked_S,Embarked_nan,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
331,332,no,45.5,0,0,113043,28.5000,C124,2.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
733,734,no,23.0,0,0,28425,13.0000,NaN,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
382,383,no,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
704,705,no,26.0,1,0,350025,7.8542,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
813,814,no,6.0,4,2,347082,31.2750,NaN,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,107,yes,21.0,0,0,343120,7.6500,NaN,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
270,271,no,NaN,0,0,113798,31.0000,NaN,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
860,861,no,41.0,2,0,350026,14.1083,NaN,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
435,436,yes,14.0,1,2,113760,120.0000,B96 B98,2.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,103,no,21.0,0,1,35281,77.2875,D26,2.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [23]:
X_test.drop('Cabin_Deck',axis=1,inplace=True)
X_test

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,encoded_Pclass,Cabin_Deck_B,Cabin_Deck_C,Cabin_Deck_D,Cabin_Deck_E,Cabin_Deck_F,Cabin_Deck_G,Cabin_Deck_T,Cabin_Deck_n
709,710,yes,third,male,NaN,1,1,2661,15.2458,NaN,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
439,440,no,second,male,31.0,0,0,C.A. 18723,10.5000,NaN,S,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
840,841,no,third,male,20.0,0,0,SOTON/O2 3101287,7.9250,NaN,S,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
720,721,yes,second,female,6.0,0,1,248727,33.0000,NaN,S,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
39,40,yes,third,female,14.0,1,0,2651,11.2417,NaN,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433,434,no,third,male,17.0,0,0,STON/O 2. 3101274,7.1250,NaN,S,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
773,774,no,third,male,NaN,0,0,2674,7.2250,NaN,C,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
25,26,yes,third,female,38.0,1,5,347077,31.3875,NaN,S,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
84,85,yes,second,female,17.0,0,0,SO/C 14885,10.5000,NaN,S,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,11,yes,third,female,4.0,1,1,PP 9549,16.7000,G6,S,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [34]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
train_df = pd.read_csv(url)

print(train_df.shape)          # (891, 12)
print(train_df.head())

(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

##Label encoding

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# (assuming train_df is your full labeled dataset)
y = train_df['Survived']

y_train, y_test = train_test_split(
    y, test_size=0.2, random_state=42, stratify=y
)

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded  = le.transform(y_test)   # ✅ no unseen-label crash

In [37]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
#fit
le.fit(y_train)
#transform
y_train_encoded=le.transform(y_train)
y_test_encoded=le.transform(y_test)

In [38]:
y_train_encoded

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1])

In [39]:
y_train

692    1
481    0
527    0
855    1
801    1
      ..
359    1
258    1
736    0
462    0
507    1
Name: Survived, Length: 712, dtype: int64